version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mastermind
      MYSQL_USER: mastermind
      MYSQL_PASSWORD: mastermind
    ports:
      - 3306:3306

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: mastermind
      POSTGRES_USER: mastermind
      POSTGRES_PASSWORD: mastermind
    ports:
      - 5432:5432

  rabbit:
    image: "rabbitmq:3-management"
#    image: itzg/rabbitmq-stomp
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#      RABBITMQ_DEFAULT_USER: "rabbitmq"
#      RABBITMQ_DEFAULT_PASS: "rabbitmq"
#      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
      - "15674:15674"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    ports:
#      - 2181:2181
#
#  kafka:
#    image: wurstmeister/kafka:2.12-2.3.0
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.45
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
