version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: mastermind
      POSTGRES_USER: mastermind
      POSTGRES_PASSWORD: mastermind
    ports:
      - 5432:5432

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
      - "15674:15674"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

#  server:
#    image: sotomski/mastermind-server
#    build: .
#    ports:
#      - 8000:8000
#    environment:
#      AMQP_URL: amqp://guest:guest@rabbit:5672/
#      DB_HOST: postgres
#
#  worker:
#    image: sotomski/mastermind-worker
#    build: ../mastermind-worker
#    environment:
#      AMQP_URL: amqp://guest:guest@rabbit:5672/
#      DB_HOST: postgres
